import React from 'react'

const mainFeatures = () => {
    return (
        <div>
            <div className='main-features'>
                <h1 className='heading'>Main Features</h1>
                <h3 className='light'>Sed fermentum, felis ut cursus various, purus velit placerat tortor, at faucibus elit purus posuere velit. Integer sit amet felis ligula.</h3>
                <div className='cards1'>
                    <div className='card-1'>
                        <img src='https://demo.themely.com/serenity/wp-content/uploads/2019/04/feature1-1.png' alt="c1" />
                        <h4>Launch Your Business</h4>
                        <p> An enim nullam tempor gravida donec enim ipsum blandit porta justo integer odio velna vitae auctor integer</p>
                    </div>
                    <div className='card-2'>
                        <img src='https://demo.themely.com/serenity/wp-content/uploads/2019/04/feature2.png' alt="c2" />
                        <h4>Easy Customization</h4>
                        <p> An enim nullam tempor gravida donec enim ipsum blandit porta justo integer odio velna vitae auctor integer</p>
                    </div>
                    <div className='card-3'>
                        <img src='https://demo.themely.com/serenity/wp-content/uploads/2019/04/feature3.png' alt="c3" />
                        <h4>Loved By Many</h4>
                        <p> An enim nullam tempor gravida donec enim ipsum blandit porta justo integer odio velna vitae auctor integer</p>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default mainFeatures
